config/routes.rb
BackboneJasmineExamples::Application.routes.draw do
  resources :todos

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  def to_json(options = {})
    super(options.merge(:only => [:id, :title, :description, :created_at, :priority, :position, :done]))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.xml
  def index
    @todos = Todo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @todos }
      format.xml  { render :xml => @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.xml
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @todo }
      format.xml  { render :xml => @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.xml
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.xml
  def create
    params.delete :action
    params.delete :controller
    @todo = Todo.create! params

    respond_to do |format|
      if @todo.save
        format.json { render :json => @todo, :status => :created, :location => @todo }
      else
        format.json  { render :json => @todo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.xml
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to(@todo, :notice => 'Todo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @todo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.xml
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.json  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackboneJasmineExamples</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Priority</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.title %></td>
    <td><%= todo.description %></td>
    <td><%= todo.priority %></td>
    <td><%= todo.position %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo.title %>
</p>

<p>
  <b>Description:</b>
  <%= @todo.description %>
</p>

<p>
  <b>Priority:</b>
  <%= @todo.priority %>
</p>

<p>
  <b>Position:</b>
  <%= @todo.position %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>